# Generated by Django 4.2.10 on 2025-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image to display on the payment page', null=True, upload_to='restaurant_backgrounds/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(blank=True, default='#0071e3', help_text='Primary brand color (hex code)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(blank=True, default='#f5f5f7', help_text='Secondary brand color (hex code)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_background_image',
            field=models.BooleanField(default=True, help_text='Display background image on payment page'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_logo_on_receipt',
            field=models.BooleanField(default=True, help_text='Display restaurant logo on payment receipt'),
        ),
    ]
