# Generated by Django 4.2.10 on 2025-05-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='square_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
