# Generated by Django 5.2 on 2025-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ordersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhillyCheesesteakPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
