# Generated by Django 5.2 on 2025-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_phillycheesesteakpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='phillycheesesteakpayment',
            name='base_amount',
            field=models.IntegerField(help_text='Base amount without tip, in cents', null=True),
        ),
        migrations.AddField(
            model_name='phillycheesesteakpayment',
            name='tip_amount',
            field=models.IntegerField(help_text='Tip amount in cents', null=True),
        ),
        migrations.AlterField(
            model_name='phillycheesesteakpayment',
            name='amount',
            field=models.IntegerField(help_text='Total amount in cents (base amount + tip)'),
        ),
    ]
