# Generated by Django 5.2 on 2025-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_phillycheesesteakpayment_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phillycheesesteakpayment',
            name='total_currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='phillycheesesteakpayment',
            name='total_money',
            field=models.IntegerField(help_text='Total amount from Square order in cents', null=True),
        ),
    ]
